- recipes-containers/container-host-config/container-host-config.bbappend
When it's enabled by:
```
PACKAGECONFIG = "transient-store"
```
a "transient_store = true" option would be added to ${sysconfdir}/containers/storage.conf, so podman will start containers with transient storage mode.
Reference about increase podman startup speed with transient storage:
https://www.redhat.com/sysadmin/speed-containers-podman-raspberry-pi
transient-store PACKAGECONFIG is disabled by default.
Related-to: TOR-3302
> container-host-config: add transient-store PACKAGECONFIG

- recipes-core/systemd/systemd_%.bbappend
The default SaveIntervalSec is set to 60 secs, it's too much wirte on disk, let's increase it to 3600 secs.
Related-to: TOR-3373
> systemd: increase SaveIntervalSec to 3600 secs

- recipes-containers/container-host-config/container-host-config.bbappend
- recipes-containers/container-host-config/container-host-config/storage.conf
The current storage.conf is based on v1.33.0 of:
https://github.com/containers/storage.git
while in podman v4.8.2, it has been upgraded to
v1.50.3-0.20231005112617-44418abb2d89 of:
https://github.com/containers/storage.git
let's sync it with podman v4.8.2.
which comprises the following commits in storage.conf:
```
42d1d9637 Run codespell on code
91da0c2be add documentation on imagestore and add a warning if set
01fccaa58 options: enable Remap-User/Group setting
e125790e9 Fix typo in storage.conf
57582350c Document transient_store in man page
522b67c94 Add new storage.conf option "transient_store"
5e9e2ba6b Revert incorrect "heeded" -> "needed" typo fix
cffa19709 fix typos and spelling
268af0001 chunked: drop host dedup feature
b64cfb4f4 Document the pull_options
17fccdc2d Clearup …
```
> container-host-config:storage.conf: sync with libpod v4.8.2

- recipes-sota/auto-provisioning/auto-provisioning/auto-provisioning.sh
If we pre-enable RAC and set the image to auto-provision itself, it could be that remote-access.service fails to start due to the fact that the device wasn't provisioned when it checked.
This way, after the device is auto provisioned, it checks if RAC is enabled and if so restarts the service.
> auto-provisioning: add service restart for remote access (RAC)

- recipes-kernel/linux/kernel-devsrc.bbappend
Adapted backport from Langdale.
Add tool files in the kernel sources needed to build kernel 5.19+ on arm64. This should solve the issue where TorizonCore Builder isn't able to build kernel modules on current Verdin AM62 releases of Torizon OS, which have kernel 6.1.
Related-to: TCB-426
> kernel-devsrc.bbappend: support arm64 kernel 5.19+ on Kirkstone

- recipes-devtools/go/go-1.20.13.inc
- recipes-devtools/go/go-1.21/CVE-2023-24531_1.patch
- recipes-devtools/go/go-1.21/CVE-2023-24531_2.patch
- recipes-devtools/go/go-1.21/CVE-2023-39318.patch
Backport required patches from go1.21 to fix CVE-2023-24531.
Backport from OE kirkstone:
https://github.com/openembedded/openembedded-core/commit/6d892c52bd5806507a05e8b6f749c54bbd9e9da6
> go: fix CVE-2023-24531

- conf/distro/include/torizon.inc
We have upgraded curl to 8.6.0, let's adjust CURLVERSION accordingly.
> torizon.inc: adjust CURLVERSION to 8.6.0

- recipes-devtools/neofetch/files/0001-neofetch-add-info-func-for-container-engine.patch
- recipes-devtools/neofetch/neofetch_7.1.0.bb
Add a info function to print out container engine and its version by checking /etc/os-release for VARIANT.
Also fix a invalid shell information in OE, sh is a symbolic link to bash.bash instead of bash in OE, handle that case by checking BASH_VERSION, provided that's present, treat sh as bash.
before the change, neofetch output:
```
OS: TorizonCore 6.6.0-devel-20240219121314+build.0 (kirkstone) aarch64
Kernel: 5.15.124-6.6.0-devel+git.f0e7afd5948f
Uptime: 1 min
Shell: sh
Resolution: 1024x768
Terminal: /dev/pts/0
CPU: (4)
Memory: 90MiB / 1989MiB
```
after the change, neofetch output:
```
OS: TorizonCore 6.6.0-devel-20240219121314+build.0 (kirkstone) aarch64
Kernel: 5.15.124-6.6.0-devel+git.f0e7afd5948f
Container Engine: Podman 4.8.2
Uptime: 1 min
Shell: bash 5.1.16
Resolution: 1024x768 …
```
> neofetch: add info func for container engine

- recipes-bsp/u-boot/u-boot-distro-boot/qemuarm64/uEnv.txt.in
Hanle the case when kernel_image_type is fitImage.
Fix: https://github.com/torizon/meta-toradex-torizon/issues/18
> u-boot-distro-boot:qemuarm64: handle fitimage

- classes/image_type_torizon.bbclass
- recipes-containers/docker-integrity-checker/files/docker-integrity-checker.sh
- recipes-devtools/neofetch/files/0001-neofetch-add-info-func-for-container-engine.patch
VARIANT can be set by end users in image recipes, so it does not always equal to "Docker/Podman", let's avoid checking it to get container engine. Instead, change to check docker/podman binaries on OS, this is safe because podman and docker are conflicting with each other, so they would be present on a same OS.
> meta: dont check VARIANT to get container engine

- recipes-devtools/neofetch/neofetch_7.1.0.bb
neofetch's Makefile does not have a clean target in it, let's set CLEANBROKEN to avoid breaking do_configure.
Fix: https://github.com/torizon/meta-toradex-torizon/issues/25
> neofetch: set CLEANBROKEN to 1

- recipes-core/initramfs-framework/files/50-am62-graphics.conf
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
For AM62, plymouth wasn't able to show the splash screen due to the framebuffer not being ready on initramfs.
So we needed to add tidss module (and it's dependencies), pwm and DSI bridges modules to make it work with our DSI to LVDS adapter. With this modification, it also made required that we insert the necessary modules for the DSI to HDMI adapter to work, thats why we also see display_connector and the lontium module.
fixes #30
> initramfs-framework: add modules to support plymouth on AM62

- recipes-extended/ostree/ostree-2024.4/0001-deploy-Ensure-boot-directory-is-open-before-accessin.patch
- recipes-extended/ostree/ostree-prepare-root.inc
- recipes-extended/ostree/ostree_2024.4.bbappend
Minor changes that make OTA updates work with secure-boot images having `composefs` enabled.
See the commit message for details.
Resolves #40
> ostree: make OTA updates possible when composefs is employed

- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-kernel/linux/linux-torizon.inc
linux-torizon.inc is being shared by linux-yocto and linux-toradex recipes, including erofs scc/cfg from there would break linux-yocto build since there is no features/erofs/erofs.scc file in yocto-kernel-cache.
Let's move it to linux-toradex-kmeta.inc.
> linux: include erofs scc/cfg from linux-toradex-kmeta.inc

- recipes-extended/rpcbind/rpcbind/0001-rpcbind.service-run-after-systemd-tmpfiles-setup.patch
- recipes-extended/rpcbind/rpcbind_%.bbappend
rpcbind.service must run after systemd-tmpfiles-setup.service, or else /var/run might not be created yet when rpcbind starts, which leads to a runtime issue.
> rpcbind: fix a systemd dependency issue

- recipes-sota/rac/rac_git.bb
This bump required many of the dependency crates to be updated as well. Most notably the recipe now uses a standard crate for russh and the related dependencies rather than cloning the repo directly.
fixes #39
> rac: bump SRCREV to latest

- recipes-images/images/torizon-core-common.inc
Commit c90cb38 dropped Pango as a dependency, which dropped the virtual/egl dependency which made the out-of-tree GPU stack for AM62 to never actually make into the final image.
This was detected using bisect and discovered due to the missing firmware files in /usr/lib/firmware in the rootfs, more specifically the rgx* binary blobs that the kernel module loads into the PVR core, which is done at runtime when the kernel module gets exercised with the correct IOCTLs (done by the libdrm component of the mesa-pvr userspace stack, present in the Torizon OS reference containers).
This commit re-introduce this dependency, much like b40b911.
Closes #49.
> recipes-image: introduce ti-img-rogue-driver as dependency

- recipes-core/systemd/systemd-conf_%.bbappend
This issue has been fixed by BSP
(https://lore.kernel.org/all/20240403212426.582727-1-jm@ti.com/), and now we can re-enable this watchdog.
closes #53
> systemd-conf: re-enable systemd HW Watchdog for Verdin AM62

- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
Bumping SRCREV with use-head-next in preparation for Torizon 6.6.1 release.
> Bump SRCREV for Kernel cache and Aktualizr

- classes/image_type_torizon.bbclass
- classes/torizon-signed.bbclass
- recipes-core/initramfs-framework/files/composefs
- recipes-core/initramfs-framework/files/plymouth
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
- recipes-extended/ostree/gen-cfs-keys.inc
- recipes-extended/ostree/ostree-torizon.inc
- recipes-images/images/torizon-core-common.inc
This initial integration covers:
- Enabling commit signing in ostree;
- Generating the keys for signing as part of the build process;
- Adding the composefs image digest to the commit metadata and signing it;
- Saving the verification (public) key into the ramdisk;
- Ensuring fsverity is enabled on the repository upon boot;
- Asking ostree to check the deployment about to be booted with the key.
Please refer to the commit messages for further details.
Note: The commits are intentionally referring to an internal ticket (TOR-3379) because I didn't want GitHub to close #46 yet (until we actually finish the integration, which requires the kernel patches for fsverity).
> Initial integration of authenticity (fs-verity) capability into the system (disabled atm)

- recipes-core/systemd/systemd-conf_%.bbappend
During release process we've re-enabled AM62 Watchdog, when we should have waited. The Kernel patch that fixes this issue is not present in the release, so we saw the reboot issues again.
> disable Verdin AM62 Watchdog

- recipes-images/images/torizon-core-common.inc
Due to BSP changes, ALSA configuration files were reworked into a new recipe.
Removing old config:
https://git.toradex.com/cgit/meta-toradex-nxp.git/commit/?h=kirkstone-6.x.y&id=54721dc86ece6b41d88f5e9de4262b575efc5393 https://git.toradex.com/cgit/meta-toradex-ti.git/commit/?h=kirkstone-6.x.y&id=d5d48dc1cc1ab54b3a498a0d5ea19646cab381ee
Adding new UCM config:
https://git.toradex.com/cgit/meta-toradex-bsp-common.git/commit/?h=kirkstone-6.x.y&id=5183100ea2bb3fe29702f96657e05f4e905433b5
> torizon-core-common: add Alsa UCM configuration

- recipes-connectivity/networkmanager/networkmanager/99-disable-uap.conf
- recipes-connectivity/networkmanager/networkmanager_%.bbappend
Since NetworkManager can't play nice with uap interfaces, we're marking them as unmanaged, so this won't affect other connections.
> networkmanager: unmanage any uap interface

- classes/image_type_torizon.bbclass
Obtaining layer information from Git was performed whenever variable EXTRA_OSTREE_COMMIT was expanded which caused metadata parsing to be very slow (20-30 minutes). Since layer information is not supposed to change during build, here we get the layer information only once by using the immediate expansion operator provided by Bitbake. This brings the parsing time to the usual values (1-2 minutes on a good machine).
Resolves #61
> image_type_torizon: parse layer information only once

- recipes-extended/fluent-bit/fluent-bit_git.bb
As per https://fluentbit.io/blog/2024/05/21/statement-on-cve-2024-4323-and-its-fix/ Fluent Bit version 2.2.3 has been updated with a backport fix for CVE-2024-4323.
Since our current Yocto recipe for Fluent Bit gets an outdated 2.2.3, updating SRCREV to get the fix should be enough. I did some quick tests and the updated recipe builds without problems.
> fluent-bit: update v2.2.3 SRCREV with backport fix for CVE-2024-4323

- recipes-images/images/torizon-core-common.inc
The image size increased 20 kB, the dependencies doensn't change.
The image was tested on a Verdin iMX8MP and cpupower tool is working.
> Change the CPU frequency tool from cpufrequtils to cpupower

- scripts/setup-environment-internal
We were presuming that any manifest name other then 'default.xml' was one of our integration manifests, thus activating the 'use-head-next' override. What was also happening was that some clients that created a top level manifest to also sync their own layers, or even Common Torizon (which uses common.xml) were wrongly interpreted as integration manifests.
Now we explicitly check for 'integration.xml' and 'next.xml' as they're our integration layers.
Closes #86
> setup-environment-internal: fix detection of integration manifests

- recipes-sota/auto-provisioning/auto-provisioning/auto-provisioning.service
Due to the device booting with an older system date, there was a race condition between auto-provisioning and the service that syncs the system time. If auto-provision would run first, the certificates would be invalid, because the current date is prior to theur validity, and the service script would fail.
Closes #90
> auto-provisioning.service: make it depend on system time sync

- recipes-sota/auto-provisioning/auto-provisioning/auto-provisioning.sh
The auto-provisioning script will now check in the config file the value of an optional boolean field called `hibernated`. If not present the `false` value is assumed.
The value is then sent to the cloud servers when registering the device. If set to `true` then the device is provisioned in hibernated mode.
This hibernated mode refers to a specific state of a registered device, where it can't receive updates from Torizon Cloud nor send data to it. Devices in this state are not counted towards a Torizon Cloud subscription.
It is not related to the power state of the device itself.
> auto-provisioning.sh: add support for hibernated mode

- recipes-core/systemd/systemd/0003-emergency-rescue.service.in-Use-torizon-specific-scr.patch
- recipes-core/systemd/systemd/torizon-recover
- recipes-core/systemd/systemd_%.bbappend
Several services can trigger rescue or emergency mode on failure. If either mode is triggered after an OTA update the device will require manual intervention. This is not desirable for Torizon OS as updates should be able to recover on their own during failure.
Add a script that will trigger a reboot that will eventually cause a rollback if emergency or rescue mode is triggered while in the middle of an update.
Related-to: TOR-3390
> systemd: Add script to recover from rescue or emergency mode

- recipes-core/systemd/systemd/0003-emergency-rescue.service.in-Use-torizon-specific-scr.patch
- recipes-extended/ostree/files/0001-update-default-grub-cfg-header.patch
In order to fix Torizon master build, we needed to refactor a systemd patch to be compliant with v256, and to add Upstream-Status to an ostree patch.
> Fix master build

- recipes-kernel/linux/linux-toradex-kmeta.inc
BSP has transitioned to used Kernel Cache for their config, and Yocto don't really play nice with multiple Caches, only applying the latest occurence on SRC_URI.
In order for both to coexist, with minimal changes, our Cache top .scc files were renamed, so Yocto won't automatically find it with its KMACHINE and KTYPE variables. Then we manually add this top level for each machine, so that it is applied along with BSP's Cache configs.
Related-to: TOR-3534
> linux-toradex-kmeta: refactor to be used with BSP's Kernel Cache

- conf/distro/include/torizon.inc
- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
In order for us to be able to use `uptane-sign` we need some changes on `meta-updater`'s `classes/image_types_ostree.bbclass` and `classes/sota.bbclass`.  
On `classes/image_types_ostree.bbclass` I've changed the task `IMAGE_CMD:garagesign` to instead of using a hardcoded `garage-sign` to call `${GARAGE_SIGN_TOOL}`.
And `${GARAGE_SIGN_TOOL}` is being defined in `classes/sota.bbclass` with `garage-sign` as its default value. This made sense to me to not disrupt other users of this layer that might still be using `garage-sign`.
Then we go into `conf/distro/include/torizon.inc` and redefine `GARAGE_SIGN_TOOL` to `uptane-sign`.
These are the only changes made on those bbclasses, all else remains as is on `meta-updater`.
And on our Aktualizr recipe, I've bumped the version used to the latest …
> Start using uptane-sign and bump to latest version

- recipes-images/images/torizon-base.inc
Related-to: TOR-3547
Closes #111
> torizon-base: add NXP's ISP support for iMX8 Plus downstream

- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
When Aktualizr is configured with BUILD_SOTA_TOOLS enabled, it will execute the get-uptane-sign.py script during build which requires a native `python3` interpreter and the `python3-requests` package. Here we amend the Aktualizr recipe to reflect that dependency.
> aktualizr-torizon: fix dependency issue when building SOTA tools

- recipes-core/base-passwd/base-passwd/0001-Add-TorizonCore-specific-groups.patch
- recipes-core/base-passwd/base-passwd/0002-Adapt-group-numbers-to-match-the-static-assignment-i.patch
- recipes-core/base-passwd/base-passwd_%.bbappend
Patch master group file in order to set the numeric IDs of some Unix groups (input, kvm, sgx) to the same values they had in previous versions of Torizon OS and as defined by the static assignments file in the OS (torizon-static-group).
This issue was detected by automated tests in LAVA.
Related-to: TOR-3538
> base-passwd: amend group numbers

- recipes-containers/docker/docker-ce/0003-Correct-panic-when-IPv4-lacks-IFA_ADDRESS-address.patch
- recipes-containers/docker/docker-ce_git.bbappend
Sometimes, especially on devices relying on modems, docker would fail to initialize and create 'docker0' interface. This is a known issue [1], that was solved upstream [2].
Since we're using an older version of docker, I've backported this fix to our layer.
[1] https://github.com/moby/moby/issues/43034
[2] https://github.com/vishvananda/netlink/pull/665
Related-to: TOR-3551
> docker-ce: backport patch correcting panic on netlink

- scripts/setup-environment-internal
Since the EULA is for NXP, there's no reason why bother people with this EULA. We simply skip it.
Closes #68
> setup-environment-internal: skip qemuarm64 and genericx86-64 EULA

- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
After the bump to Kernel 6.6 we got a build error that some kernel modules could not be found. After checking TI Kernel config, either those configs were now builtin or non-existent, so they were removed.
Plymouth (boot splash screen) was tested and is working for both DSI to LVDS and DSI to HDMI.
> initramfs-framework: remove unnecessary kernel modules from ramfs

- recipes-sota/aktualizr-torizon/files/aktualizr-torizon.service
Torizon OS sends device monitoring data directly via fluent-bit. Therefore the data proxy is no longer needed.
Related-to: TOR-3245
> aktualizr-torizon: Disable data proxy by default

- conf/distro/include/torizon.inc
- recipes-bsp/u-boot/u-boot-distro-boot.bbappend
- recipes-bsp/u-boot/u-boot-distro-boot/uEnv.txt.in
This is part of the work of enabling hardening on BSP images and it depends on related work on layer `meta-toradex-bsp-common` and on [meta-toradex-security](https://github.com/toradex/meta-toradex-security/pull/63).
At the moment, changes to the former are under review by the BSP team and due to that I'm leaving this as draft to prevent the merge but it should be ready for review.
> Enable hardening on BSP images (scarthgap)

- conf/distro/include/torizon.inc
- recipes-bsp/u-boot/u-boot-distro-boot.bbappend
- recipes-bsp/u-boot/u-boot-distro-boot/uEnv.txt.in
This is part of the work of enabling hardening on BSP images and it depends on related work on layer meta-toradex-bsp-common and on https://github.com/toradex/meta-toradex-security/pull/65.
At the moment, changes to the former are under review by the BSP team and due to that I'm leaving this as draft to prevent the merge but it should be ready for review.
> Enable hardening on BSP images (kirkstone)

- recipes-connectivity/avahi/avahi_%.bbappend
Since avahi-daemon uses the hostname to create the address, it needs
to be correctly set beforehand.
And since 'set-hostname' service is already ordered to run before
network-pre, we can make sura avahi-daemon only runs aftter that target,
and this way we'll be sure to use the correct hostname.
Related-to: TOR-3562
> avahi: make avahi depend on network-pre target

- scripts/setup-environment-internal
The script checks if the number of arguments is greater than 1 and prints the usage and exits. If the user does not check the script code it makes difficult to understand why the script is exiting.
> setup-environment-internal: add error message for too many arguments

- recipes-sota/rac/files/client.toml
- recipes-sota/rac/files/remote-access.service
- recipes-sota/rac/rac_git.bb
This release of RAC includes the possibility of receive messages through D-Bus to poll the server for new sessions. These messages are sent by the tzn-mqtt bridge (now included as a dependency for the remote-access service) and thus we can significantly increase the intervals to check the HTTP server, reducing bandwidth.
Still, we keep the periodically checking the HTTP server regardless of new messages on D-Bus as a fallback solution.
This default configuration is an example and can be changed by users to fit their particular needs, specially in the case where an applicaiton is bandwidth sensitive.
Note that this change also moves the rac repository to the Torizon organization and also slightly updates the comment in regards to AUTOREV.
Related-to: TOR-3522
This change was tested with …
> Update RAC recipe

- recipes-sota/rac/files/client.toml
- recipes-sota/rac/files/remote-access.service
- recipes-sota/rac/rac_git.bb
This release of RAC includes the possibility of receive messages through D-Bus to poll the server for new sessions. These messages are sent by the tzn-mqtt bridge (now included as a dependency for the remote-access service) and thus we can significantly increase the intervals to check the HTTP server, reducing bandwidth.
Still, we keep the periodically checking the HTTP server regardless of new messages on D-Bus as a fallback solution.
This default configuration is an example and can be changed by users to fit their particular needs, specially in the case where an applicaiton is bandwidth sensitive.
Note that this change also moves the rac repository to the Torizon organization and also slightly updates the comment in regards to AUTOREV.
Related-to: TOR-3522
> Update RAC recipe: cherry-pick of #153 into master

- conf/distro/include/torizon.inc
In oe-core the TCLIBCAPPEND variable was deprecated, so we need to remove it from our layer.
[1] https://git.openembedded.org/openembedded-core/commit/?id=992ba784c168710328749fd61a0e2869df519dea
> torizon.inc: remove TCLIBCAPPEND variable

- recipes-extended/fluent-bit/files/custom-empty.conf
- recipes-extended/fluent-bit/files/fluent-bit.conf
- recipes-extended/fluent-bit/fluent-bit_git.bb
If the users have to modify fluent-bit.conf to add their customizations, that adds a maintenance burden requiring them to merge in changes on every new release.  With this change, user customizations can be stored in seperate include files negaiting that merge step.
> fluent-bit: Setup include files for easy customization.

- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-sota/rac/rac_git.bb
> bump SRCREV to latest for Torizon OS 6.8.0 quarterly release

- recipes-sota/rac/rac_git.bb
Due to the implementation of MQTT, rac requires Rust 1.75+, while we are currently using version 1.70, which caused build failures on Torizon 6. Therefore, it was decided to bump RAC only on scarthgap and not on kirkstone.
This reverts commit ffaaef66df05537ac77aca0edbe3f9cff8743abc.
Related-to: TOR-3516
> rac: revert "rac: bump SRCREV to latest"

- conf/template/bblayers.conf
- files/torizon-static-group
- files/torizon-static-passwd
fTPM under OP-TEE requires the meta-tpm layer from meta-security to be added to bblayers.conf, and for the tss group and user to exist. Since we use useradd-staticids, we need to add the group and user manually.
> Add static group, user, and meta-tpm bblayer for fTPM OP-TEE support

- recipes-core/udev/files/95-toradex-dma.rules
- recipes-core/udev/udev-toradex-rules.bbappend
Set read and/or write access to the dma_heap using video group. Access is required for using g2d renderer on Apalis iMX8 and Colibri iMX8X.
Related-to: TCCP-830
> udev: add dma rules

- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
- recipes-sota/aktualizr-torizon/files/aktualizr-tmpfiles.conf
Files in /tmp get periodically cleaned-up via systemd-tmpfiles. If this happens to aktualizr related files then, aktualizr will fail to work properly until it gets restarted.
Related-to: TOR-3614
> aktualizr-torizon: Exclude aktualizr tmpfiles from systemd cleanup

- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
- recipes-sota/aktualizr-torizon/files/aktualizr-tmpfiles.conf
Files in /tmp get periodically cleaned-up via systemd-tmpfiles. If this happens to aktualizr related files then, aktualizr will fail to work properly until it gets restarted.
Related-to: TOR-3614
> aktualizr-torizon: Exclude aktualizr tmpfiles from systemd cleanup (kirkstone)

- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
- recipes-sota/aktualizr-torizon/files/aktualizr-tmpfiles.conf
Files in /tmp get periodically cleaned-up via systemd-tmpfiles. If this happens to aktualizr related files then, aktualizr will fail to work properly until it gets restarted.
Related-to: TOR-3614
> aktualizr-torizon: Exclude aktualizr tmpfiles from systemd cleanup (master)

- classes/cfs-signed.bbclass
Make immediate assignment rather using the override syntax to add the cfs-signed and cfs-support overrides to variable DISTROOVERRIDES. This allows one to check that variable in situations where the immediate value is needed, for example in conditional includes/requires.
Minor change just to be consistent with similar changes being done in `meta-toradex-security`:
https://github.com/toradex/meta-toradex-security/pull/83
> cfs-signed: use immediate assignment to DISTROOVERRIDES

- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
Make initramfs-module-composefs only recommend rather than strictly depend on initramfs-module-overlay and initramfs-module-erofs. With this, now the corresponding drivers (overlay, erofs) can be compiled as built-in or as modules. Before there was the assumption that those drivers would be always modules but that assumption was broken on scarthgap where the overlay driver became built-in due to changes at the kernel side that in turn lead meta-virtualization to apply certain configuration fragments to the kernel, one of which impacting how the overlay driver was built.
The changes here should only impact images utilizing composefs, which currently means those inheriting class "torizon-signed".
> initramfs-framework: no longer depend on overlay being a module

- recipes-extended/ostree/ostree-2021.6/0005-curl-Make-socket-callback-during-cleanup-into-no-op.patch
Fixing the backported patch, as it was missing '#include <stdbool.h>'.
We caught this issue as today's Jenkins builds all failed while building ostree.
Related-to: TOR-3649
> [Kirkstone] ostree: fix ostree curl fetcher patch

- recipes-extended/ostree/files/0001-mount-Allow-building-when-macro-MOUNT_ATTR_IDMAP-is-.patch
- recipes-extended/ostree/files/0002-mount-Allow-building-when-macro-LOOP_CONFIGURE-is-no.patch
- recipes-extended/ostree/ostree_%.bbappend
This reverts commit 72922783bb0057c3929bdad9caa73f2638d6937c.
Unfortunately we cannot yet remove the patches for dealing with missing MOUNT_ATTR_IDMAP and LOOP_CONFIGURE because ostree 2024.5 still refers to composefs v1.0.3 (as a submodule) whereas the patches have been applied upstream only in v1.0.4.
@EdTheBearded Sorry, I gave you wrong information that led you to this removal but now checking the errors in CI I realized we actually couldn't remove the patches on scarthgap.
> Revert "ostree: removing unnecessary composefs patches"

- recipes-bsp/u-boot/u-boot-distro-boot/uEnv.txt.in
- recipes-extended/ostree/files/0002-Add-support-for-the-fdtfile-variable-in-uEnv.txt.patch
- recipes-extended/ostree/files/0005-Add-support-for-kernel_image_type-in-uEnv.txt.patch
- recipes-extended/ostree/ostree_%.bbappend
This fixes an issue with the rollback feature that happens when the kernel image type changes during an OS update; for example, when one switches from a standard (non secboot) to a secboot image.
See commit messages for further details.
> Fix for OS rollback not working when kernel image type changes on update

- recipes-bsp/u-boot/u-boot-distro-boot/uEnv.txt.in
- recipes-extended/ostree/files/0002-Add-support-for-the-fdtfile-variable-in-uEnv.txt.patch
- recipes-extended/ostree/files/0004-Add-support-for-kernel_image_type-in-uEnv.txt.patch
- recipes-extended/ostree/ostree_%.bbappend
Same as https://github.com/torizon/meta-toradex-torizon/pull/191, but for the master branch.
Notice I kept the patch number from scarthgap for the moment. Just let me know if you prefer to change it already.
> Fix for OS rollback not working when kernel image type changes on update (master)

- recipes-core/systemd/systemd_%.bbappend
This variable has been deprecated on version 255, in favor of 'nonarch_libdir', and removed from systemd's recipe.[1]
We caught this issue on our latest Jenkins build of master:
```
12-08:13:23:31  ERROR: systemd-1_256.8-r0 do_package: QA Issue: systemd: Files/directories were installed but not shipped in any package:
12-08:13:23:31    /systemd
```
[1] https://github.com/openembedded/openembedded-core/commit/c89b34401dfbe65de5a32bf8b4ef32902d868ce1
> [Master] systemd: fix usage of deprecated rootlibexecdir variable

- recipes-core/udev/files/10-toradex-net-rename.rules
- recipes-core/udev/files/toradex-net-rename.sh
Since the MAC address range we have is almost finished, Toradex has bought a new range of MAC addresses and is utilizing it with its new Aquila AM69.
For t his reason, we had to adapt our udev rule and refactor the script to accommodate this new range.
Related-to: TOR-3630
> udev: toradex-net-rename: refactor rename script and rules for AM69

- recipes-bsp/u-boot/u-boot-distro-boot.bbappend
The MR that added the fuse bank words [1], also added an issue on do_compile task [2]. Since the arithmetic operator `$((...))` is not supported by bitbake inside a `$(...)` command expression. So 'let' was used to update the for loop index, which is not supported by POSIX shell.
So the fix was to add another task, 'get_fuse_bank_word', made in python and scheduled to run before 'do_compile'. This way, this task processes the BANK_WORD variable, produces the u-boot script string to be replaced later and store it inside 'FUSE_BANK_WORDS'. Then we go into our 'do_compile:append' and simply replace our u-boot script with the newly generated 'FUSE_BANK_WORDS.
Also all bank word variables are now a python tuple, so that we can process them.
[1] …
> u-boot-distro-boot: fix do_compile task to generate fuse bank words

- recipes-bsp/u-boot/u-boot-distro-boot.bbappend
For unsupported machines, BANK_WORD is an empty string and since this was not being handled on this function we had an exception in this function that caused the build to fail.
Now if BANK_WORD is empty, we return early with "" as well.
Related-to: TOR-3664
> u-boot-distro-boot: fix 'get_bank_word_internal' with empty strings

- recipes-core/initramfs-framework/files/composefs
- recipes-core/initramfs-framework/files/rootfs
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
- recipes-extended/ostree/files/ostree-repo-config.service
- recipes-extended/ostree/files/ostree-repo-config.sh
- recipes-extended/ostree/ostree-prepare-root.inc
- recipes-extended/ostree/ostree_%.bbappend
The main difference between BCoT (basic chain of trust) and ECoT (extended chain of trust) is the addition of the root filesystem protections to ensure integrity and authenticity, both of which achieved by the use of composefs.
In this PR we add a the capability of upgrading a legacy OSTree installation (based on hard links) to one backed by composefs. Overall, the upgrade method introduced here involves:
- Implementation inside the initial ramdisk to enable fsverity on the filesystem and on the individual files in the OSTree repository.
- A systemd service responsible for changing the OSTree repository configuration (which is itself kept outside of OSTree) to enable both composefs and fsverity on the OSTree/libostree side.
For further details, please refer to the commit messages. …
> Add support for upgrading from BCoT to ECoT

- recipes-bsp/u-boot/u-boot-distro-boot.bbappend
- recipes-bsp/u-boot/u-boot-distro-boot/uEnv.txt.in
- Fix a bug in the format of variable `fuse_bank_word`.
- Make fuse additions conditional: now the additions will be present only on supported NXP machines when building a `tdx-signed` image.
- Store valid value in `fuse_val_N` in case of fuse read errors.
For details, please refer to the commit messages.
> Improvements and bug fix to the fusing feature

- recipes-bsp/u-boot/u-boot-toradex-ti_%.bbappend
'require u-boot-ota.inc' was removed from this bbappend due to some build errors:
```
ERROR: u-boot-toradex-ti-1_2024.04+git-r0 do_deploy: Recipe u-boot-toradex-ti is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
/workdir/torizon-7.x.y-integration/build-torizon/deploy/images/verdin-am62/u-boot-initial-env.raw
(not matched to any task)
/workdir/torizon-7.x.y-integration/build-torizon/deploy/images/verdin-am62/u-boot-version.json
(not matched to any task)
Please adjust the recipes so only one recipe provides a given file.
```
Because 'u-boot-ota.inc' is appending to all 'do_deploy' tasks, we end up installing those filles more than once (since for TI, it is a multiarch build). And since we can't just add an ':k3r5' …
> u-boot-toradex-ti: add U-Boot fragments to enable fallback

- recipes-kernel/linux/linux-toradex-kmeta.inc
Bumping linux-toradex-kmeta so that we get the TOR-3733 fix into our release build.
Related-to: TOR-3733
> linux-toradex-kmeta: bump SRCREV to latest

- classes/image_type_torizon.bbclass
Currently, the warning for non-versioned layers involved in a build is not much helpful:
```
WARNING: Failed to get layers information. Exception: <class 'bb.process.ExecutionError'>
```
With this commit, the message will point which layer is causing it and what is the specific error that happened. E.g.:
```
WARNING: Failed to get layers information. Caused by layer at /workdir/torizon-7/layers/meta-iotedge-torizon. Exception: Execution of 'export PSEUDO_UNLOAD=1; git rev-parse HEAD' failed with exit code 128:
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
> image_type_torizon: improve warning for non-versioned layers

- recipes-sota/config/aktualizr-default-sec.bb
- recipes-sota/config/files/bl_actions.sh
- recipes-sota/config/files/common_actions.sh
- recipes-sota/config/files/fuse_actions-in.sh
Tested on Verdin i.MX8MP and Apalis i.MX8. Also did a test build for AM62 just to make sure the build still works on non-NXP machines.
Marking as draft for now till after the quarterly release is done, but should be ready for review otherwise.
> Add new HAB fuse update type

- recipes-kernel/linux/linux-torizon.inc
This is an attempt to solve an issue with the PREEMPT-RT builds where the build of the kernel (along with device-trees and overlays) does not match the build of the kernel modules. Specifically, what does not match is the string responsible for defining the kernel ABI version which in turn also defines the name of the directory containing the kernel and kernel modules.
To try and solve the issue, here we modify the do_patch task to make it forcefully set the commit date of the last commit which is supposed to be the commit applying the RT patches. Normally applying those patches produces different hashes every time because the said patches do not have date information in then leading the kgit-s2q tool to use the current date on the commit produced by the patching operation.
Related-to: …
> Attempt to solve "Kernel modules not working correctly on preempt-rt images"

- recipes-kernel/linux/linux-torizon.inc
Turns out the logic to check if the RT patches dates are correctly set as introduced by commit "linux-torizon.inc: make preempt-rt commit dates deterministic" failed with upstream kernels. Here we amend the logic to deal with that.
Related-to: TOR-3656
> linux-torizon.inc: adapt RT patches check to upstream distro

- recipes-kernel/linux/linux-torizon.inc
Same as https://github.com/torizon/meta-toradex-torizon/pull/213 plus https://github.com/torizon/meta-toradex-torizon/pull/216 for the master branch.
> Solve "Kernel modules not working correctly on preempt-rt images" (master)

- conf/layer.conf
- conf/machine/include/am62xx-evm.inc
- dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend
- dynamic-layers/meta-ti-bsp/recipes-kernel/linux/linux-ti-staging%.bbappend
- recipes-bsp/u-boot/u-boot-distro-boot.bb
- recipes-bsp/u-boot/u-boot-distro-boot/boot.cmd.in
- recipes-bsp/u-boot/u-boot-distro-boot/uEnv.txt.in
- recipes-bsp/u-boot/u-boot-rollback/am62xx-evm/bootcommand.cfg
- recipes-extended/ostree/ostree_%.bbappend
- recipes-images/images/torizon-base.inc
- recipes-sota/ostree-kernel-initramfs/ostree-kernel-initramfs_%.bbappend
- scripts/lib/wic/canned-wks/torizon-am62xx-sota.wks
Add initial Torizon OS support for the AM62x Starter Kit Evaluation Module via Common Torizon distro, using the TI BSP. In addition to this layer (meta-toradex-torizon), the following Yocto layers are necessary in order to build the image:
- meta-virtualization
- meta-networking 
- meta-python
- meta-oe
- meta-filesystems
- meta-ti-extras
- meta-ti-bsp
- meta-arm 
- meta-arm-toolchain
- meta
- meta-poky
- meta-yocto-bsp
- meta-updater
`DISTRO` should be set to `common-torizon`
`MACHINE` should be set to `am62xx-evm`
In `conf/local.conf` append the following line at the end of the file:
```
include conf/machine/include/am62xx-evm.inc
```
Build the image with:
```
bitbake torizon-docker
```
> Add support for TI AM62x Starter Kit EVM (SK-AM62B-P1) board on Common Torizon

- dynamic-layers/meta-imx-bsp/recipes-graphics/mali/mali-imx_%.bbappend
- recipes-images/images/torizon-base.inc
We need the firmware as the kernel module expects it in specific places of the
root filesystem, so it cannot be dynamically deployed from containers as the
rest of the graphical stack is.
On the imx8 and am62 for example the firmware is installed via 'driver' recipes
(kernel-module-imx-gpu-viv and ti-img-rogue-installer), on the imx95, however,
it comes from userspace portion, thus we need the bbappend to only install the
firmware, nothing else (no libEGL, libGLES etc...).
This follows the same logic as commits a7ec4b08 and b40b9114.
Note that I haven't 100% tested this commit besides a build as I need to actually build the graphical userspace to trigger the kernel module to load the firmware, but having it in `lib/firmware` is, from my understanding, enough.
Of course, the rest of the …
> imx95: install mali firmware (mali_csffw.bin) in the rootfs

- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
This is expected to solve a build issue with torizon-signed images where the following error message is output in the build logs:
ERROR: initramfs-ostree-torizon-image-1.0-r0 do_rootfs: Cannot find any SPDX file for document
http://spdx.org/spdxdocs/kernel-module-display-connector-<version>-<sha>
The immediate cause for the problem comes from the initramfs-framework: do_create_runtime_spdx task not being executed even when initial ramdisk undergoes modifications between two builds. Unfortunately the root cause is still a mistery. However, a simple solution employed here is by making the initramfs-framework:do_create_runtime_spdx task "rdepend" on the corresponding task of the kernel.
Besides the above, also change how we set the dependencies to the required kernel modules when composefs …
> initramfs-framework: fix torizon-signed SPDX build issue

- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
Bump the `aktualizr-torizon` version being used (just to synchronize with TorizonCore Builder).
> aktualizr-torizon: bump SRCREV to latest

- recipes-kernel/linux/linux-torizon.inc
Move RT commits amendment to a postfunc of the do_patch task to avoid depending on the base implementation of that task being necessarily a shell function.
Related-to: TOR-3755
> linux-torizon.inc: move RT commits amendment to postfunc

- recipes-sota/config/files/fuse_actions-in.sh
The firmware file generated from "get-firmware-info" should be in canonical form. It was not doing so before, so this should correct the behavior.
> aktualizr-default-sec: fix fuse action handler behavior

- recipes-sota/rac/rac_git.bb
- recipes-sota/tzn-mqtt/tzn-mqtt_git.bb
Now that it is using MQTT, data usage is more tolerable and we can have it enabled by default on Torizon OS builds.
Related-to: TOR-3750
> rac: enable RAC by default

- recipes-sota/auto-provisioning/auto-provisioning/auto-provisioning.sh
Some users when auto-provisioning, power down the system once they see the auto-provisioning service exit successfully. However, in some cases this can cause the files created from the provisioning process to not be fully written to disk, resulting in 0-byte files upon next boot.
Therefore, add some explicit syncs to improve this behavior. Also make use of a temp directory to improve the overall atomicity of the process.
Related-to: TOR-3743
Sames as: https://github.com/torizon/meta-toradex-torizon/pull/217 but for Kirkstone
> auto-provisioning: improve behavior with power cuts (kirkstone)

- recipes-kernel/linux/linux-torizon.inc
Same as https://github.com/torizon/meta-toradex-torizon/pull/233 but for the master branch.
>  linux-torizon.inc: move RT commits amendment to postfunc (master)

- docs/README-x86.md
Now that we've created our internal manifests for x86 builds, we should also add the steps on how to use this on our public documentation.
Related-to: TOR-3759
> docs/README-x86: update with manifest information

- scripts/setup-environment
Sometimes the 'unset' command will output some error that it wasn't able to unset a variable, and will pollute the output we give.
So now we suppress the error output of the command.
Related-to: TOR-3763
> setup-environment: discard 'unset' error messages

- dynamic-layers/meta-imx-bsp/recipes-kernel/linux/linux-imx_%.bbappend
- recipes-kernel/linux/linux-torizon.inc
To apply a Kernel fragment to NXP's Kernel, we need to add it to 'DELTA_KERNEL_DEFCONFIG', so that it can be manually applied to the generated .config file.
Related-to: TOR-3754
> imx95: add torizon.cfg fragment to NXP's Kernel

- docs/README-rzv2l.md
Fix missing meta-virtualization dependency, and missing arguments for "./kas-container shell".
> docs: Update Renesas rzv2l docs

- README.md
- conf/distro/include/common-torizon.inc
- conf/machine/include/am62lxx-evm.inc
- conf/machine/include/am62pxx-evm.inc
- conf/machine/include/am62xx-evm.inc
- conf/machine/include/am62xx.inc
- docs/README-ti.md
- dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/am62/bootcommand.cfg
- recipes-bsp/u-boot/u-boot-rollback/qemuarm64/bootcommand.cfg
- scripts/setup-environment
Also a minor refactor on the AM62 machine includes, to avoid duplicating code, fix a potential issue on `bootcommand`, where we were assuming default addresses.
And added the AM62L entry in the README file, as well as an alternate flashing method.
Please check the commit messages for more info
> Add support for TI's AM62L EVM

- recipes-devtools/fastfetch/fastfetch_git.bb
- recipes-extended/fluentbit/files/0001-lib-Do-not-use-private-makefile-targets-in-CMakelist.patch
- recipes-extended/fluentbit/files/0002-flb_info.h.in-Do-not-hardcode-compilation-directorie.patch
- recipes-extended/fluentbit/files/0003-CMakeLists.txt-Revise-init-manager-deduction.patch
- recipes-extended/fluentbit/files/0004-chunkio-Link-with-fts-library-with-musl.patch
- recipes-extended/fluentbit/files/0004-wasm-avoid-cmake-try_run-when-cross-compiling.patch
- recipes-extended/fluentbit/files/0005-Use-posix-strerror_r-with-musl.patch
- recipes-extended/fluentbit/files/0005-cprof_encode_text.c-fix-wrong-pointer-assignment.patch
- recipes-extended/fluentbit/fluentbit_3.2.1.bb
- recipes-sota/greenboot/greenboot_git.bb
- recipes-support/composefs/composefs_1.0.8.bb
fastfetch: v2.29.0 to v2.38.0 - changelog: https://github.com/fastfetch-cli/fastfetch/releases)
fluentbit: v3.1.9 to v3.2.1 (backported from meta-oe's master as is) - changelog: https://fluentbit.io/announcements/older-versions/
greenboot: v0.15.7 to v0.15.8 - changelog: https://github.com/fedora-iot/greenboot/releases/tag/v0.15.8
composefs: v1.0.5 to v1.0.8 - (backported from meta-oe's master as is) - changelog: https://github.com/composefs/composefs/releases/tag/v1.0.8
Related-to: TOR-3512
> Scarthgap maintenance 

- conf/machine/include/common-am62xx.inc
- dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/libubootenv_%.bbappend
- dynamic-layers/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging_%.bbappend
We have some 'meta-ti-bsp' custom .bbappends on dynamic-layers, but the issue here is that Toradex's HW also uses this layer so we end up apllying those configurations as well.
In the end, it resulted in 'fw_printenv' not working properly, since the configuration file for TI is different from Toradex, which caused greenboot to not work properly and the OS rollback process to fail altogether.
Now we add a new override for TI's AM62 devices in our 'common-am62xx.inc' file, namely 'common-ti', since there's not unique override on TI's BSP, and 'ti-soc' that was used was common to both BSP's. So now, on TI's specific .bbappends, we use the 'common-ti' override, to make sure we're using Common Torizon distro and TI machine.
Related-to: TOR-3777
> am62xx: make bbappend changes only apply to TI's AM62 builds

- scripts/lib/setup-devices/setup-environment-ti
Quick fix to properly close an 'if' statement in the script. My previous PR caused this issue, sorry about the mess.
> scripts: fix setup-environment-ti syntax error

- recipes-connectivity/hostapd/files/hostapd.service
- recipes-connectivity/hostapd/hostapd_%.bbappend
Aquila AM69 is using the ath11k Linux driver, which does not support separate wireless interfaces for station mode and access point mode. So following the BSP changes [1], we add the necessary commands to hostapd.service to create the uap0 interface.
[1] https://git.toradex.com/cgit/meta-toradex-demos.git/commit/?h=scarthgap-7.x.y&id=de062b56b74134216934747e60760226e48997c9
Related-to: TOR-3801
> hostapd: add custom hostapd.service for Aquila AM69

- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-sota/rac/rac_git.bb
> Bump SRCREV to latest for Torizon OS 7.2.0 quarterly release

- conf/distro/include/torizon.inc
When we did 86343936 (conf/distro: refactor torizon distro to support Common Torizon), we left behind some assignments in "torizon.inc" that were already present in "base-distro.inc" (included by the former). Here we fix this situation.
Related-to: TOR-3828
P.S.: I made this related to TOR-3828 ("Expected bootargs do not match actual args on signed images (apalis-imx6, colibri-imx6, colibri-imx6ull)") because my [previous PR](https://github.com/torizon/meta-toradex-torizon/pull/270) did not solve the issue with the boot arguments and the reason was these duplicated assignments (that I didn't notice were present).
> torizon.inc: remove duplicated assignments

- classes/torizon_base_image_type.inc
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
On some occasions, the `torizon-signed` image output by the build system won't boot showing an error message like this during boot:
```
ostree-prepare-root: No valid signatures found for public key
ERROR: There's no '/dev' on rootfs.
```
From what I could gather, the reason for this is a mismatch between the (private) key used for actually signing the composefs digest (that is stored as commit metadata in the OSTree repo) and the (public) key stored in the initial ramdisk. This situation can happen because the build system (Bitbake) keeps a stamp file associated with the tasks responsible for (a) signing the OSTree commit and (b) installing the public key into the ramdisk and those tasks don't necessarily run if the key files change (due to the stamp file).
The solution introduced here is …
> Fix torizon-signed generation with regards to the composefs keys

- recipes-sota/rac/rac_git.bb
Some git environments are configured with safe.bareRepository=explicit [1], causing the do_fetch step to fail when attempting to git fetch the tough SRC_URI. Let's fix this by adding the missing .git suffix in the URI to ensure it is a bare repository.
```
$ bitbake rac
...
WARNING: rac-0.0+git-r0 do_fetch: Failed to fetch URL git://github.com/toradex/tough;protocol=https;branch=rac;name=tough;destsuffix=tough, attempting MIRRORS if available
ERROR: rac-0.0+git-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; ... LANG=C git -c gc.autoDetach=false -c core.pager=cat -c safe.bareRepository=all fetch -f --progress https://github.com/toradex/tough refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* failed with …
```
> rac: fix SRC_URI for tough

- recipes-core/systemd/systemd_%.bbappend
With Scarthgap the install location of 00-create-volatile.conf was changed from /etc to /usr/lib.
Update our bbappend to point to this new install location.
Related-to: TOR-3838
> systemd: Fix volatile logs

- recipes-core/systemd/systemd_%.bbappend
With Scarthgap the install location of 00-create-volatile.conf was changed from /etc to /usr/lib.
Update our bbappend to point to this new install location.
Related-to: TOR-3838
Same as: https://github.com/torizon/meta-toradex-torizon/pull/278
But for the master branch.
> systemd: Fix volatile logs (master)

- recipes-kernel/linux/linux-toradex-kmeta.inc
> Bump SRCREV to latest for Torizon OS 7.3.0-devel-202506 monthly pre-release

- conf/machine/include/am62lxx-evm.inc
Cherry-picking #281 to master.
(cherry picked from commit 6d3e307f221958c8c3348177357d7de572df0fa4)
> [Master] am62l: fix missing bootloader binary

- scripts/lib/setup-devices/setup-environment-imx
- scripts/lib/setup-devices/setup-environment-intel
- scripts/lib/setup-devices/setup-environment-renesas
- scripts/lib/setup-devices/setup-environment-ti
Builds were using a lot of disk space, and was affecting negatively our CI.
On this change I've fixed the sstate-cache directory for TI builds, placing it on root directory instead of inside the build folder.
Also I've added a line that inherits `rm_work` bbclass for our builds, so that we cleanup a bit afterwards and use less disk space.
> [Common] Use less disk space during builds

- recipes-core/initramfs-framework/files/50-imx8-graphics.conf
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
Due to BSP's change on linux-toradex-kconfig [1], a regression was introduced on Torizon OS where the splash screen was no longer appearing during boot on iMX8 devices (Colibri and Verdin).
This was due to the config CONFIG_IMX_IRQSTEER now being set to module, so it would be missing during splash initialization, on initramfs.
Now we add the module to our initramfs for it to be inserted before initializing plymouth.
[1] https://git.toradex.com/cgit/linux-toradex-kconfig.git/commit/?h=main&id=2bbba4e35cc4ac9f5ee0a6a44b5a6aa2a60324ba
Related-to: TOR-3803, TOR-3807, TOR-3837
> initramfs-framework: add irq_imx_irqsteer module to iMX8 initramfs

- recipes-connectivity/modemmanager/modemmanager/0001-quectel-disable-qmi-unsolicited-profile-manager-even.patch
- recipes-connectivity/modemmanager/modemmanager/0002-broadband-modem-qmi-quectel-fix-task-completion-when.patch
- recipes-connectivity/modemmanager/modemmanager_%.bbappend
With the update to ModemManager version 1.22.0 we now have some Quectel modems failing to use QMI properly:
ModemManager[1178]: [modem0] power state updated: on ModemManager[1178]: [modem0] (quectel) modem reset detected, triggering reprobe ModemManager[1178]: [modem0] (quectel) modem reset detected, triggering reprobe .
.
.
ModemManager[1178]: [modem0] failed waiting for final state: Too much time waiting to get to a final state ModemManager[1178]: [modem0] failed enabling modem: Operation was cancelled ModemManager[1178]: [modem1] couldn't start initialization: Transaction timed out ModemManager[1178]: [modem1] fatal error initializing: Fatal error: modem is unusable
This has been fixed upstream with the 2 patches we backport here:
ModemManager[1139]: [modem0] power state updated: on …
> modemmanager: Fix Quectel modems initialization bug

- recipes-core/initramfs-framework/files/50-imx8-graphics.conf
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
Related-to: TOR-3863
(cherry picked from commit 898b81d901122cb59a8b080dcb2a5bec4312dd72)
> [Master] initramfs-module-kmod: add missing modules to enable native LVDS

- recipes-core/initramfs-framework/files/50-imx8-graphics.conf
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
> initramfs-module-kmod: add missing modules to enable native LVDS

- classes/ostree_layer_revision_info.bbclass
- classes/torizon_base_image_type.inc
- recipes-images/images/torizon-base.inc
The function get_layer_revision_information is executed 350+ times, as its encompassing class image_type_torizon is added to IMAGE_CLASSES. However, it calculates exactly the same layer revision info for every image in the same build. The commit sha's of the layer repositories don't change during a build. In short, the function must be executed only once. We achieve this by moving the function into its own class ostree_layer_revision_info and inheriting it via torizon-base.inc in the single image recipe requiring the layer revision info (e.g., torizon-minimal or torizon-docker). The time for parsing recipes drops from over 10 minutes to roughly 30 seconds.
Cherry picked from commit 9daddac6acca47f51dda1d5be9475c3e61bdc575
> get_layer_revision_information: reducing parsing time from 10min to 30s

- conf/distro/include/base-distro.inc
- conf/distro/include/torizon.inc
base-distro.inc removes features like 3g, alsa, nfc, and wayland from DISTRO_FEATURES. It makes impossible adding these features in a distro extending torizon.conf. Once an item is removed from a BitBake variable, it can never be appended again.
The solution is to assign the removed features to a new variable DISTRO_FEATURES_REMOVE in torizon.inc and :remove its contents from DISTRO_FEATURES in base-distro.inc.
Client code can remove features from DISTRO_FEATURES_REMOVE and append the features to DISTRO_FEATURES. DISTRO_FEATURES_REMOVE is an extension point for torizon.conf similar to IMAGE_FSTYPES_REMOVE. Now, clients can extend the distro conf torizon.conf.
> torizon.conf: Extending distro with formerly removed distro features

- recipes-images/images/torizon-base.inc
This add support to AM62P hardware in the same way we had for AM62 target. Without this we don't have accelerated features while using Chromium container.
Related-to: TCCP-1046
> images/torizon-base.inc: Add rogue drivers for AM62P target

- recipes-core/images/initramfs-ostree-torizon-image.bb
- recipes-core/initramfs-framework/initramfs-graphics.inc
> initramfs-graphics: Add missing modules for Aquila AM69 splash screen

- conf/distro/include/base-distro.inc
Add the "opengl" feature back to DISTRO_FEATURES_REMOVE (conditioned on override "imx-generic-bsp"); this was removed by mistake. With this, the feature should not be present on the final DISTRO_FEATURES.
> base-distro: re-add opengl to the list of removed features on i.MX
