- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
Bumping toradex-kernel-cache and aktualizr-torizon to the latest hash.
> Monthly release bump

- recipes-sota/rac/rac_git.bb
A following compilation error was observed:
|   duplicate key `olpc-cjson` in table `patch.https://github.com/toradex/tough`
that is due to a sed syntax trying to append a 'olpc-cjson' line to ${CARGO_HOME}/config, but it has to delete it before hand, otherwise, there is a risk when do_compile runs, it will append multiple 'olpc-cjson' lines to ${CARGO_HOME}/config.
also a following compilation error was observed:
|   Unable to update https://github.com/toradex/tough?branch=rac#28c2deb2
that is due to OE's cargo running in offline mode, it can not fetch any sources through internet, so we should not use 'rac' branch as SRCREV_tough, it has to match the exact commit hash of tough dependency in torizon-rac's Cargo.lock file.
Also let's move the code modifying ${CARGO_HOME}/config to …
> rac: fix some compilation problems

- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
- recipes-sota/rac/rac_git.bb
> Bump hashes in preparation for monthly release

- conf/layer.conf
> layer.conf: make it compatible with scarthgap

- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
- recipes-sota/rac/rac_git.bb
> Bump SRCREV to latest

- conf/distro/include/torizon.inc
- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
Cherry-picking #99 into Scarthgap branch.
Related-to: TOR-3496
> Start using uptane-sign and bump to latest version

- recipes-images/images/torizon-base.inc
> torizon-base: add disk partition utility for tests

- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
> bump SRCREV to latest for Torizon OS 6.8.0-devel-202409 monthly

- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
- recipes-sota/rac/rac_git.bb
> bump SRCREV to latest for Torizon OS 7.0.0-devel-202409 monthly

- classes/image_type_torizon.bbclass
- recipes-core/systemd/systemd-conf_%.bbappend
- scripts/setup-environment-internal
> Add Aquila AM69

- classes/image_type_torizon.bbclass
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
- recipes-extended/ostree/gen-cfs-keys.inc
Minor fix, though the original code shouldn't ever cause any issues.
> Fix cfs-signed override check

- classes/image_type_torizon.bbclass
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
- recipes-extended/ostree/gen-cfs-keys.inc
Minor fix, though the original code shouldn't ever cause any issues.
> Fix cfs-signed override check (master branch)

- recipes-kernel/linux/linux-toradex-kmeta.inc
> Bump SRCREV to latest for Torizon OS 7.0.0 quarterly release

- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
- recipes-sota/rac/rac_git.bb
> Bump SRCREV to latest for Torizon OS 7.1.0-devel-202411 monthly pre-release

- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
- recipes-sota/rac/rac_git.bb
> Bump SRCREV to latest for Torizon OS 7.1.0-devel-202412 monthly pre-release

- recipes-sota/rac/files/client.toml
> rac: enable DBus client by default

- recipes-bsp/u-boot/u-boot-fuse/0001-toradex-adjust-ahab_status-exit-code-behavior.patch
- recipes-bsp/u-boot/u-boot-fuse/0001-toradex-adjust-hab_status-exit-code-behavior.patch
> u-boot-fuse: fix patch Upstream-Status tag

- recipes-bsp/u-boot/u-boot-distro-boot.bbappend
- recipes-bsp/u-boot/u-boot-distro-boot/uEnv.txt.in
- recipes-bsp/u-boot/u-boot-fuse.inc
- recipes-bsp/u-boot/u-boot-fuse/0001-toradex-add-new-command-to-determine-HAB-AHAB-closed.patch
- recipes-bsp/u-boot/u-boot-fuse/0001-toradex-adjust-ahab_status-exit-code-behavior.patch
- recipes-bsp/u-boot/u-boot-fuse/0001-toradex-adjust-hab_status-exit-code-behavior.patch
- recipes-bsp/u-boot/u-boot-toradex_%.bbappend
- recipes-bsp/u-boot/u-boot_%.bbappend
Cherry pick changes from PR #190 into master.
> [Master] Cherry pick changes from PR #190

- classes/cfs-signed.bbclass
- conf/distro/include/torizon.inc
- recipes-bsp/u-boot/u-boot-distro-boot.bbappend
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
A couple of updates that were missing on the master branch.
> Update master branch from PRs #144, #175 and #176

- recipes-core/initramfs-framework/files/composefs
- recipes-core/initramfs-framework/files/rootfs
- recipes-core/initramfs-framework/initramfs-framework_1.0.bbappend
- recipes-extended/ostree/files/ostree-repo-config.service
- recipes-extended/ostree/files/ostree-repo-config.sh
- recipes-extended/ostree/ostree-prepare-root.inc
- recipes-extended/ostree/ostree_%.bbappend
Same as #197, but for the master branch.
**NOTE**: Leaving this as draft until #200 is merged.
>  Add support for upgrading from BCoT to ECoT (master)

- recipes-bsp/u-boot/u-boot-distro-boot.bbappend
- recipes-bsp/u-boot/u-boot-distro-boot/uEnv.txt.in
Same as #203 but for the master branch.
> Improvements and bug fix to the fusing feature (master)

- recipes-sota/auto-provisioning/auto-provisioning/auto-provisioning.sh
(cherry picked from commit c394d6fcc43c437fd0b67caab030e7ffd133d7e9)
> auto-provisioning.sh: add support for hibernated mode

- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
> aktualizr-torizon: bump SRCREV to latest

- recipes-kernel/linux/linux-toradex-kmeta.inc
- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
> Bump SRCREV to latest for Torizon OS 7.2.0-devel-202502 monthly pre-release

- recipes-kernel/linux/linux-toradex-kmeta.inc
> Bump SRCREV to latest for Torizon OS 7.2.0-devel-202503 monthly pre-release

- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
> Bump SRCREV to latest for Torizon OS 7.3.0-devel-202505 monthly pre-release

- scripts/setup-environment
Add SMARC iMX8, iMX95 and Verdin AM62P.
> Add new toradex devices to setup-environment scripts

- classes/image_type_torizon.bbclass
- classes/torizon_base_image_type.inc
- dynamic-layers/meta-toradex-ti/recipes-bsp/u-boot/u-boot-toradex-ti_%.bbappend
Build and deploy bootloader binaries appropriate for OTA updates plus some code simplifications to help with maintenance. Please refer to the individual commit messages for detail.
Related-to: TOR-3737
Signed-off-by: Rogerio Guerra Borin <rogerio.borin@toradex.com>
> Integrate bootloader updates for the verdin-am62/verdin-am62p

- classes/image_type_torizon.bbclass
- classes/torizon_base_image_type.inc
- dynamic-layers/meta-toradex-ti/recipes-bsp/u-boot/u-boot-toradex-ti_%.bbappend
Same as https://github.com/torizon/meta-toradex-torizon/pull/295, but for the master branch.
Related-to: TOR-3737
Signed-off-by: Rogerio Guerra Borin <rogerio.borin@toradex.com>
> [Master] Integrate bootloader updates for the verdin-am62/verdin-am62p

- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
Cherry-pick of https://github.com/torizon/meta-toradex-torizon/pull/260 
I don't have a test build environment for torizon-master, so I'm leaning on the CI to validate this.
> aktualizr-torizon: Enable D-Bus interface in Aktualizr

- README.md
Forwarding https://github.com/torizon/meta-toradex-torizon/pull/321 to the `master` branch
> docs: Rework README for clarity and usability

- recipes-sota/aktualizr-torizon/aktualizr-torizon_git.bb
> Bump SRCREV to latest for Torizon OS 7.4.0-devel-202509 monthly pre-release

- recipes-extended/rpcbind/rpcbind_%.bbappend
Same as: https://github.com/torizon/meta-toradex-torizon/pull/335
But, for the master branch.
> rpcbind: Disable systemd service
